### ISSUE TITLE
Compression and Encryption functionality?

### ISSUE THREAD

**Issue by lonnietc** [LTRData/ImDisk#11]
Hello,

I am exploring ImDisk for use in a potential project and think that it is really an amazing piece of work from the testing that I have done so far. 

In addition to using it as a normal RAMDISK, I also have some ideas on how it might be used as part of a specialized IPC communication channel across independent applications written in different languages as well as for some other exciting work that I am trying to do as well.

On thing that I was wondering is that I know ImDisk can save images since I was playing with the ImDisk TK (toolkit) but was wondering if there might be some type of compression settings so that upon saving the image then it would be compressed and upon loading then it would be decompressed.

The other question is that I would like to investigate if there was any type of encryption functionality already built into ImDisk as that is a feature that I would like to use, but if it is not then maybe I could investigate adding it in some way but wanted to check first.

Truly awesome work you have done along with the original developer and it still holds great potential for a lot of good use.

Thanks and have a great day.

**Comment by lonnietc** [comment]
Hello again,

On the related compression question and for the second use-case that I have in mind, I was thinking about being able to have a ramdisk that effectively starts at zero, or at least being very small, and dynamically grows in use which could then be saved as it grows.

Or perhaps, mounting an image and it would dynamically grow as items were put into the ramdisk after which it could be saved at the new size and dismounted to be mounted at a later time.

Just some thoughts that I had on this.

**Comment by LTRData** [comment]
If you are looking for mounting image files and not RAM disks, this is actually pretty easy. When you create a new image file you can use the `sparse` option:
`imdisk -a -f C:\imagefile.img -s 40G -o sparse -m R: -p "/fs:ntfs /q /y"`
This will create a 40 GB image file with sparse allocation that takes up almost no space at all from start, but the system allocates space for it as needed.

Regarding encryption, the same developer as developed ImDisk Toolkit has also developed an encryption layer for ImDisk:
https://sourceforge.net/projects/proxycrypt/

**Comment by lonnietc** [comment]
@LTRData Thank you so very much for getting back to my questions so quickly and I think that these might be exactly what I am looking for since I really like ImDisk a lot and want to use it for a unique approach for the project.

Have a great day
