### ISSUE TITLE
There is some sort of problem when accessing elements inside an ImDisk based disk.

### ISSUE THREAD

**Issue by jrmoore** [LTRData/ImDisk#12]
Hi, I'm sorry about the undescriptive bug report title, but I couldn't think of anything better.

A while ago [I filed a report at ImDisk Toolkit's tracker](https://sourceforge.net/p/imdisk-toolkit/tickets/49/), through which I'm using the ImDisk driver.

Basically, I have setup a RAM disk that's always recreated at startup with user temporary directories pointing to it (i.e., R:\Temp), 8 GB, using AWE and being dynamic in terms of memory. It works great most of the times, but some applications seem to have a hard time working with it.

These are some of the error messages that are shown:

![Intel graphics Installer](https://user-images.githubusercontent.com/311922/177319841-a73e9fcc-bdc9-498f-ad23-974b296d892a.png)

![oneAPI checking for space](https://user-images.githubusercontent.com/311922/177319863-716b0f36-f30b-4af7-b343-5dffb7286827.png)

The first one belongs to the current graphic driver installer from Intel, it states that the application is in an unauthorized location, whatever that means. Also from Intel, their oneAPI compiler package installer complains X MB of space are needed, even when it was virtually empty. In both cases I had to move things out of the RAM disk for them to work.

The behavior is similar in a way to what I encountered years ago when Process Hacker was updating and %TEMP% pointed to inside the RAM disk, I reported it over at their forums, and their developer kind of explained what the problem was, so I could report it properly, but I completely forgot about it. The reply is here, in case it's still relevant (it seems to have to do with IOCTLs): https://wj32.org/processhacker/forums/viewtopic.php?t=3419#p10644

![ON1](https://user-images.githubusercontent.com/311922/177319876-ac656d6b-a229-4eb3-8248-a2c5390c79c8.png)

I don't know if you guys are aware of the issue(s), but I just stumbled upon this project here and seeing there seems to be active development I thought of referencing it here too. The third picture belongs to another case that exhibits the same behavior, I had to temporarily switch the TEMP environmental variables to a real disk to be able to continue with that installation.

Could you please look into it? Don't hesitate to let me know if you need more data samples, or you want logs of some sort, I would gladly do trial and error for you with debug builds of the driver. It needn't be signed, I could self sign them and make sure Windows trusts that signature to do the testing, or enable installation of unsigned drivers for the tests.

Thank you for your time by the way.

**Comment by LTRData** [comment]
This is a very well known problem. ImDisk is based on a very old driver design and is not recommended on modern versions of Windows. It lacks lots of features that many modern applications expect to be supported.

**Comment by jrmoore** [comment]
Oh! I see, because I saw a recent comment about updating the toolchain of the solution I thought it was in active development.

The problem is hard to fix then, right? Do you know of any other RAM disk implementation that would be suitable for use on modern versions of Windows? I was using ImDisk through the ImDisk Toolkit as my go to, I always keep temp folders over there and use that drive for most things.

It's too bad it can't be fixed.

**Comment by jrmoore** [comment]
Sadly, at least for me, Arsenal Image Mounter doesn't seem to be a good fit, I find it very complicated and seems to be oriented to something else entirely (forensics?).

It's odd that I find myself in a situation when I don't even know where to click, but I felt that way with it. Plain RAM disk creation seems to be an afterthought, there are a couple of entries in some menus for it one that just asks for its size and allocates the whole block all at once and another to use a VHD template (?). No option to choose drive letter, autocreation on boot, AWE so memory isn't paged, dynamic memory usage, etc.

On first boot there's a dialog about a driver being needed and it offers to auto install it, but if we wanted to uninstall it... I couldn't find any option for it in the UI. Although looking at the GitHub repo I found many other things in there that aren't linked to in the site, like a command line binary to uninstall the driver (the graphical one throws an exception for some reason). So there's that possibility.

There seems to be a low level binary to interact with the driver as well, `aim_ll.exe`, not included in the official distribution, but when I ran it with `/?` to get some help on its usage I was overwhelmed by the options and wouldn't even know what to do 😟.

To be honest, even if ImDisk is outdated in its design and lacks many things I find it way more user friendly thanks to the ImDisk Toolkit's RAM configuration UI. It's just tick, tick, tick, set size, click OK and we're done.

![image](https://user-images.githubusercontent.com/311922/177781466-c10102f7-f578-4f34-a82b-4c890b7c2c39.png)
![image](https://user-images.githubusercontent.com/311922/177781579-502996a6-71ff-491e-bebf-f06bf6e18223.png)

For now I think I will continue to use ImDisk, even if unreliable while I look for a suitable replacement. But thanks for the recommendation! Since Arsenal's is in active development I'm sure something more user friendly will appear at some time, perhaps with an installer as well, so I'll keep my eye out for it.

**Comment by LTRData** [comment]
Thanks! I hope that someone could create a user interface for such features like was done with ImDisk Toolkit. I remember that the interest for ImDisk really took off when ImDisk Toolkit was made available, because it was a bit complicated to use before.

Personally I do not really find a sync feature useful but I realize that some users really like to synchronize data back and forth between their RAM disks and permanent storage instead of just using RAM disks for temporary storage. It is a bit difficult to implement though and it has taken a large amount of work for ImDisk Toolkit developer to implement it there too. I cannot see that happen in AIM in any near future.

But we have lots of other interesting features in the pipeline and a new release coming out soon. For instance, a feature to expose physical disks attached to the system as virtual image files, to make it easier to analyze disks and file systems, create image files etc.
