### ISSUE TITLE
Request: CSO Support

### ISSUE THREAD

**Issue by 60fpshacksrock** [LTRData/ImDisk#14]
Would adding CSO support from maxcso be possible?

**Comment by LTRData** [comment]
No new features are added to ImDisk anymore, it is only available for use on legacy systems, where newer alternatives are not available. But to support this image file format, it should be possible to implement it for example in DiscUtils libraries or as some other kind of DLL, which would make it available to Arsenal Image Mounter, if someone is interested.

**Comment by 60fpshacksrock** [comment]
I have never heard of Arsenal Image Mounter before. I must check this out.

All right, I will request this feature for Arsenal Image Mounter. Thanks.
