### ISSUE TITLE
Unable to run 2.1.1 installer

### ISSUE THREAD

**Issue by Thilas** [LTRData/ImDisk#2]
With the latest release version (v2.1.1), I can't run the installer on Windows 10 or 2019. I get the following error:
![image](https://user-images.githubusercontent.com/3749820/140637333-4ede18d7-56d4-4551-b0b5-0ffc9827e8e8.png)

But if I unzip the sfx and run `install.cmd`, it works all fine. `runwaitw.exe` is where it is expected.

Any idea?

**Comment by LTRData** [comment]
Ah, sorry, yes the packaging process failed and picked up the wrong self extraction module. Fixed now!

**Comment by Thilas** [comment]
Confirm it's alright, https://github.com/Thilas/chocolatey-packages/issues/22 is now fixed as well. Thanks!

**Comment by Gitoffthelawn** [comment]
I just wrote #3, and perhaps this explains what I saw.

For the release of https://ltr-data.se/files/imdiskinst.exe from a few days ago (v2.1.1 as it was published on 2021-11-05, not the v2.1.1 as it is currently published... confusing... please always update version numbers when making *any* changes!), I extracted all the files from https://ltr-data.se/files/imdiskinst.exe, right-clicked on the `.inf` file, and selected `Install` from the context menu.

Did this correctly install ImDisk, or do I need to uninstall v2.1.1 from a few days ago and install v2.1.1 from today?

**Comment by LTRData** [comment]
It is the same version. No need to update anything, no files changed.

**Comment by LTRData** [comment]
I made a note about this in the version history now to clarify that no files have been changed in the package, it still installs the same 2.1.1 files as the failing package contained.

**Comment by Gitoffthelawn** [comment]
Thank you!  BTW, if you want, you could also release as a zip file.  I found installing by right-clicking on the `.inf` file to be very convenient and more transparent about what was about to happen.

**Comment by LTRData** [comment]
If you extract the files in that way I would recommend to run the install.cmd file instead of just right-click on the .inf file. The install.cmd script calls the .inf file anyway but also do some preparations such as checks for existing drivers in use, unload existing drivers etc so that upgrade operations work correctly and show appropriate error message boxes if anything need to be taken care of before upgrade.

But anyway, yes a zip file is a good idea too. We distribute a zip archive for Arsenal Image Mounter drivers and that is useful sometimes and it would probably be useful sometimes here too.

**Comment by Gitoffthelawn** [comment]
Great. Thank you for the tips and for your openness to creating a zip version!

Real quick question: Is there a way to open the ImDisk control panel without triggering a UAC prompt (without disabling UAC)?

**Comment by LTRData** [comment]
No, not anymore. Not like it used to work in older versions. Previously you could open it without administrative privileges but it would instead fail for example to safely dismount file system before device removal etc which could be a bit risky, lead to data corruption and leave devices behind that could not be removed. To avoid all this and all confusion it caused, this was a reasonably easy way to solve most of it.

**Comment by Gitoffthelawn** [comment]
Yes, a UAC prompt is nothing compared to data loss or instability.

I imagine one could create a scheduled task to workaround the UAC, but IMHO it's probably not worth it.  Most people probably don't need to open the ImDisk control panel every day after they get things configured to their liking.
