### ISSUE TITLE
Is there a way to make my new memory virtual disk invisible to other users on the same machine?

### ISSUE THREAD

**Issue by adream100** [LTRData/ImDisk#20]
I'm running ImDisk on a Windows Server2022 machine that someone else is using remotely. 
I use the command line: imdisk -a -s 4G -m R: -p "/fs:ntfs /q /y" 
to create an R disk and it works fine. This is a great tool !
I want this R disk can only be used by me, no one else can see. Can it be done? Thank you.

**Comment by LTRData** [comment]
Yes, but it requires more steps. 
```
imdisk -a -s 4G
dosdev R: \Device\ImDisk0
format R: /fs:ntfs /q /y
```

You can get dosdev.exe from my web site:
https://ltr-data.se/opencode.html

**Comment by adream100** [comment]
I test and it works.
