### ISSUE TITLE
In Windows 10, when setting virtual memory on the disk created by LmDisk, there will be an error during startup.

### ISSUE THREAD

**Issue by gmij** [LTRData/ImDisk#22]
In Windows 10, when setting virtual memory on the disk created by LmDisk, there will be an error during startup.

**Comment by LTRData** [comment]
Could you explain a bit more what command you used and what error message you got?

**Comment by gmij** [comment]
Ok,. 
![1](https://github.com/LTRData/ImDisk/assets/22893579/0552996a-21cb-4a6c-a730-b628c8e235b3)
![2](https://github.com/LTRData/ImDisk/assets/22893579/7fed5410-ee67-4857-be10-efaaa5e9538a)
![3](https://github.com/LTRData/ImDisk/assets/22893579/1b39e55d-7107-49fc-a1a8-fb39efb56eef)
![4](https://github.com/LTRData/ImDisk/assets/22893579/c965ffcf-8a4b-440f-b1b9-2b6bea4d4056)

**Comment by LTRData** [comment]
Oh, you are using ImDisk Toolkit. The respiratory for that project is located here: 
https://sourceforge.net/projects/imdisk-toolkit/

Please post your question there instead! 

Thank you!
