### ISSUE TITLE
CCboot + windows server 2019 = ISCSI disk read only

### ISSUE THREAD

**Issue by Buster14** [LTRData/ImDisk#24]
Hi, so i'm using this ccboot diskless program which basically mounts ISCSI drives from server to clients.

Problem is, when using windows 10 image, the drives appear normally.

But in windows server 2019 image, all the ISCSI drives are all read only. 

Now i just found out in ccboot client folder it has imdisk folder, and i have uploaded the content here, 

[imdiskinst.zip](https://github.com/user-attachments/files/16903847/imdiskinst.zip)

So most likely they are using imdisk to create ramdisk drive, then ISCSI the drive somehow...
I have asked them but they have no idea what caused this.
So i was wondering, if imdisk has issue with iscsi drive creation in windows server 2019?
I have tried changing the SAN rule to online-all, but still no luck..

**Comment by LTRData** [comment]
ImDisk drives are not affected by SAN policy or similar rules set for storage on servers. But in general, there are lots of issues like this with ImDisk on modern versions of Windows and I would strongly suggest migrating to another storage virtualization solution.

**Comment by Buster14** [comment]
Ran imdisk --version
and it says imdisk 2.09 compiled 2015

What if i replace it with newer version?
I'm curious since it works fine on windows 10, but it won't work on windows server 2019 
(which is supposed to based on windows 10)
And your doc says it works with win 10..

How would i re-apply the settings then after updating?

**Comment by LTRData** [comment]
There are very few changes between latest versions and I doubt anything relevant to this issue. It should be possible to simply run the installer and let it update all files and then restart the computer. It does not change any settings or similar, it just updates driver files and library files and similar.
