### ISSUE TITLE
Please add icon in system tray menu for hot mount and unmount drives.

### ISSUE THREAD

**Issue by korenevskiy** [LTRData/ImDisk#26]
1. Please add icon in system tray menu for hot mount(enabled) and unmount(disabled) drives.
or 
add control with use CMD(PoserShell) command.
_So that the disks do not hang in RAM and do not take up space. And at the right moment, on request, through the icon menu, you could download and use RAM._
2. Also, when creating a virtual disk in the manager, add a check mark that allows you to create icons on the desktop to enable and disable a new virtual disk.

**Comment by LTRData** [comment]
Thanks for your suggestion, but ImDisk is very old now and I only fix bugs and similar when needed. I no longer develop new features.

**Comment by korenevskiy** [comment]
but [Arsenal-Image-Mounter](https://github.com/ArsenalRecon/Arsenal-Image-Mounter) not support mode RAMDisk.
And this app "ImDisk"  works great

**Comment by LTRData** [comment]
> but [Arsenal-Image-Mounter](https://github.com/ArsenalRecon/Arsenal-Image-Mounter) not support mode RAMDisk. And this app "ImDisk" works great

Arsenal Image Mounter has the same RAM disk features as ImDisk. You can essentially just replace your current imdisk.exe command line with aim_ll.exe and it does the same thing. Or, if using the GUI, you have RAM disk features on Advanced menu.

**Comment by korenevskiy** [comment]
Sorry. This program is completely paid. It is a pity that it does not have a basic free component. for example, a 6Gb RAM disk is free, and more is paid.
