### ISSUE TITLE
ImDisk doesn't seem to be compatible with Firefox

### ISSUE THREAD

**Issue by Gitoffthelawn** [LTRData/ImDisk#6]
This is odd, but I triple-checked what I experienced, and here is the STR.

1. Install Firefox v95.0.2 on a Win7 box.
2. Install ImDisk v2.1.1.
3. Create an ImDisk volume using the command: `imdisk.exe -a -m G: -s 1g -p "/fs:exFAT /v:ImDisk /q /y"`
4. Create a Firefox profile on the ImDisk volume.
5. Install [Bonjourr](https://github.com/victrme/Bonjourr) in the Firefox profile and configure it as the new tab page.
6. Open a new tab & notice that the Bonjourr page will never appear due to a storage error. (It works correctly on a non-ImDisk volume.)
7. Install [Tabliss](https://github.com/joelshepherd/tabliss) in the Firefox profile and configure it as the new tab page.
8. Open a new tab.
9. Notice that the Tabliss page *does* appear.
10. Now change settings in Tabliss.
11. Notice that none of the Tabliss settings will be saved due to a storage I/O error (`IO error: Incorrect function. (os error 1) ExtensionStorageSync.jsm:66`).  This only happens on an ImDisk volume.

I also ran the same tests with the ImDisk volume formatted as NTFS.  The same errors occurred.

**Comment by LTRData** [comment]
There are lots of compatibility issues with ImDisk on modern versions of Windows. Please refer to warnings in readme file and on the official website about this.

**Comment by Gitoffthelawn** [comment]
Thanks.  I thought Win7 would be old enough to be okay.

I had installed ImDisk by extracting all the files and right-clicking on the `.inf` file, and selecting the `install` context menu item.  (This was before our conversation about running the `cmd` file.)

Given how I installed it, what's the best way to completely uninstall it?

**Comment by LTRData** [comment]
It is still a modern application that probably expects things like volume mount manager etc. Such applications will fail with ImDisk on any version of Windows.

ImDisk was originally written for NT 3.51 and NT 4.0 and also works pretty okay on Windows 2000 and XP. But from Vista and onwards it starts getting complicated. Many applications that are written to work on Vista and later do not work with ImDisk because of this old design and lack of support for more recent disk and volume features.

You can still use the uninstall script from the package. It uninstalls what is installed and ignores other things.

**Comment by Gitoffthelawn** [comment]
Thanks.  It's interesting how ImDisk has so many positive reviews written well after the days of Windows XP. 

Regarding the uninstall script, you're referring to `uninstall_imdisk.cmd`, correct?

**Comment by LTRData** [comment]
It still has lots of use cases where it works perfectly all the way up to Windows 11. It is extremely light-weight and easy to install and uninstall. I very rarely use it myself nowadays but it happens for example when I am on Windows versions that do not have iso image mounting features built-in and want to mount an iso image to install an application from it. It is also useful in forensics or recovery scenarios in some cases where you just want to recover files from an image.

Yes, uninstall_imdisk.cmd is the one I thought of!

**Comment by Gitoffthelawn** [comment]
I opened opened an admin command prompt window, and ran `uninstall_imdisk.cmd`.  This was the output:

```
ImDisk Virtual Disk Driver Uninstall

Number of existing ImDisk virtual disks: 0
The ImDisk Virtual Disk Driver Helper service is stopping.
The ImDisk Virtual Disk Driver Helper service was stopped successfully.


The AWE Memory Allocation Driver service was stopped successfully.


The ImDisk Virtual Disk Driver service was stopped successfully.

ERROR: The process "imdsksvc.exe" not found.
```

Does the error at the end indicate a problem?


Also, after the uninstall (and a reboot), I noticed that these files remain:

```
c:\Windows\assembly\NativeImages_v4.0.30319_32\ImDiskNet\...\ImDiskNet.ni.dll
c:\Windows\assembly\NativeImages_v4.0.30319_32\ImDiskNet\...\ImDiskNet.ni.dll.aux
```

What's the best way to remove them?  Can they just be deleted, or does one or both of them need to be unregistered (or some other technique)?

Thanks for your help on this.

**Comment by LTRData** [comment]
The error message from the uninstall script is no problem. It just means that the service was not running at that point, which is the case if it has not been used.

The other files you have found under C:\Windows\assembly were not installed by ImDisk Virtual Disk Driver installer, imdiskinst.exe or anything embedded in that package. You must have got them from somewhere else. They are the .NET API for ImDisk so if you have installed or run something that use ImDisk through .NET API, that is probably where they come from. They are safe to delete now when ImDisk is anyway not installed anymore.

**Comment by Gitoffthelawn** [comment]
> The error message from the uninstall script is no problem. It just means that the service was not running at that point, which is the case if it has not been used.

Thanks.  The service had been used, but not since rebooting.  That's what you mean, correct?

> The other files you have found under C:\Windows\assembly were not installed by ImDisk Virtual Disk Driver installer, imdiskinst.exe or anything embedded in that package. You must have got them from somewhere else. They are the .NET API for ImDisk so if you have installed or run something that use ImDisk through .NET API, that is probably where they come from. They are safe to delete now when ImDisk is anyway not installed anymore.

That's really odd.  I'm trying to think of anything that would have used ImDisk.  There isn't anything on that box that mentioned using a RAM disk.  Although they didn't mention it, the only 3 possibilities I can think of are Sandboxie Plus, Avira antivirus, and Avast antivirus.  Each of those was installed at some point a couple years ago.

Is it safe to just delete the files, or best to use `regasm.exe` or `gacutil.exe` (or even `regsvr32.exe`) to remove them (and adjust any related counters)?

**Comment by LTRData** [comment]
ImDisk is used for lots of other things than just RAM disks. I know for example that it has been embedded with some applications to mount iso images for installation and upgrade scenarios.

You could of course use `regasm.exe /unregister` and then `gacutil.exe /u` to remove COM registration and global assembly cache references for it. (You cannot use `regsvr32.exe` on .NET assemblies, instead `regasm.exe` is used for corresponding COM registration operations.)

**Comment by Gitoffthelawn** [comment]
> ImDisk is used for lots of other things than just RAM disks. I know for example that it has been embedded with some applications to mount iso images for installation and upgrade scenarios.

Ah, I didn't know this.  Thank you.

> You could of course use `regasm.exe /unregister` and then `gacutil.exe /u` to remove COM registration and global assembly cache references for it. (You cannot use `regsvr32.exe` on .NET assemblies, instead `regasm.exe` is used for corresponding COM registration operations.)

Thanks.  I've been looking through the logs, registry modification timestamps, backups, and the data from a few forensics tools, and it looks like it was almost certainly Avira.

**Comment by Gitoffthelawn** [comment]
I've still been trying to find a RAM Disk that is compatible with Firefox.

I recently heard good things about OSFMount, and I like it's feature set.  Unfortunately, it had the same problems as ImDisk.

I wasn't completely surprised, as it looks like it likely has some code in common with ImDisk, but because OSFMount has been updated quite a bit, and I didn't read any complaints about it, I gave it a try.

2 quick questions:  
1. To your knowledge, does OSFMount have code in common with ImDisk?
2. Do you have any recommendations for a RAM Disk that will likely work with Firefox?

TIA

**Comment by LTRData** [comment]
Yes, if I recall correctly OSFMount was originally based on ImDisk. Even though it had probably evolved from that over time it does not surprise me that it might share some limitations related to the driver design.

We have other more modern drivers that can replace ImDisk on modern versions of Windows and that have much better compatibility. For example Arsenal Image Mounter has a command line tool that I made with a very similar syntax so that it should be fairly easy to move from ImDisk to AIM.
https://github.com/ArsenalRecon/Arsenal-Image-Mounter

**Comment by Gitoffthelawn** [comment]
Thanks for the quick reply!

Is [aim_cli.exe](https://github.com/ArsenalRecon/Arsenal-Image-Mounter/blob/master/Command%20line%20applications/aim_cli.exe) a CLI tool that you use with AIM, or does it have AIM included?

**Comment by LTRData** [comment]
No, `aim_ll.exe` is the one that corresponds to `imdisk.exe`. But you need to install the driver first. There are a couple of different ways to do that. Easiest is probably `ArsenalImageMounterCLISetup.exe` or `ArsenalImageMounterCLISetup.exe` which include the driver embedded in the exe files. As an alternative you can download and extract `DriverFiles.zip` and use `aim_ll.exe --install` to install drivers from the extracted zip file.
