### ISSUE TITLE
Installation fails on Windows 11 for ARM64

### ISSUE THREAD

**Issue by T-640** [LTRData/ImDisk#8]
Hello!

When installation comes to the point of installing the inf file a message box with text "Installation failed." pops up. The installer, the script in zip file, and choosing the "Install" option when clicking on the inf file all fail with this error. All attempts were performed with administrator privileges. Files were downloaded from https://www.ltr-data.se/

Manually loading the drivers via the `sc create` and `sc start` and executing the corresponding cpl file works though, I have managed to get them all to load that way and create partition in RAM.

Not sure if that matters, but the system is a guest OS in a virtual machine which is disconnected from the Internet.

**Comment by LTRData** [comment]
Yes, this is a known problem. I wrote something about this in the reboot.pro forum a while ago. Unfortunately, the forum seems down right now. I will move the FAQ to a file here on Github as well soon so that it will be possible to get even when the forum is down.

**Comment by Gitoffthelawn** [comment]
Is this just an issue with ARM64 processors?

**Comment by LTRData** [comment]
> Is this just an issue with ARM64 processors?

Yes, that is right. The script in the installer does not work on ARM or ARM64 because the included tools that the script uses do not work correctly (or some of them no at all) on these architectures.

**Comment by Gitoffthelawn** [comment]
Thank you for the details.  Much appreciated.
